export const PRODUCT_IS_ADDED_TO_CART = "PRODUCT_IS_ADDED_TO_CART";
export const PRODUCT_IS_ADDED_TO_CART_FROM_FILTERED_ARRAY =
  "PRODUCT_IS_ADDED_TO_CART_FROM_FILTERED_ARRAY";
export const PRODUCT_IS_REMOVED_FROM_CART = "PRODUCT_IS_REMOVED_FROM_CART";
export const PRODUCT_IS_REMOVED_FROM_CART_FOR_FILTERED_ARRAY =
  "PRODUCT_IS_REMOVED_FROM_CART_FOR_FILTERED_ARRAY";
export const SHOW_DIALOG = "SHOW_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
export const REDUCE_QUANTITY = "REDUCE_QUANTITY";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const REDUCE_PRODUCT_AMOUNT = "REDUCE_PRODUCT_AMOUNT";
export const INCREASE_PRODUCT_AMOUNT = "INCREASE_PRODUCT_AMOUNT";
export const TOTAL_AMOUNT = "TOTAL_AMOUNT";
export const SET_SORT_BY_VALUE = "SET_SORT_BY_VALUE";
export const SORT_BY = "SORT_BY";
export const SORT_BY_FILTRED_PRODUCTS = "SORT_BY_FILTRED_PRODUCTS";
export const RATE_PRODUCT = "RATE_PRODUCT";
export const ADD_FILTER_BY_CATEGORIES = "ADD_FILTER_BY_CATEGORIES";
export const ADD_FILTER_BY_CATEGORIES_FROM_FILTERED_PRODUCTS =
  "ADD_FILTER_BY_CATEGORIES_FROM_FILTERED_PRODUCTS";
export const REMOVE_FILTER_BY_CATEGORIES = "REMOVE_FILTER_BY_CATEGORIES";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const TOGGLE_IS_FETCHING = "TOGGLE_IS_FETCHING";
